baseURL = 'http://dsal3389.xyz'
languageCode = 'en-us'
title = 'dsal3389'
theme = 'hugo-bearcub'

enableRobotsTXT = true

[permalinks]
blog = "/:slugorfilename/"
tags = "/post/:slug"

[[menu.main]]
name = 'home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'posts'
pageRef = 'posts'
weight = 20

[params]
  title = "test"
  description = "Daniel Sonolian's website"
