baseURL = 'http://dsal3389.xyz'
languageCode = 'en-us'
title = 'dsal3389'
theme = 'hugo-dead-simple'

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[params]
hideMadeWithLine = true

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Blog'
pageRef = 'blog'
weight = 20

[[menu.main]]
name = 'random'
pageRef = 'random'
weight = 30

