baseURL = 'http://dsal3389.xyz'
languageCode = 'en-us'
title = 'dsal3389'
theme = 'hugo-theme-til'

enableRobotsTXT = true
showGraph = true

[params.author]
  name = 'Daniel Sonbolian'
  email = 'dsal3389@gmail.com'

[params.home]
  showRecentPosts = true
  recentPostsLimit = 3

[params.footer]
  showthemeCredit = true

[params.robotstxt]
  blockAI = true
