baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'dsal3389'
theme = 'hugo-simple'

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[params]
hideMadeWithLine = true

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Blog'
pageRef = 'blog'
weight = 20

[[menu.main]]
name = 'learning'
pageRef = 'learning'
weight = 30

